#!/bin/bash

APPNAME=dhcp
APPVER=4.3.5
DOWNVER=`echo $APPVER |sed 's/\./-/g'`
CONFDIR=$srvCONFDIR/$APPNAME

EXTERNAL_DEP=""
INTERNAL_DEP="radvd"


mod_main(){
 if [ ! -f $srvDOWNDIR/$APPNAME-$APPVER.tar.gz ]; then
  run "wget https://www.isc.org/downloads/file/$APPNAME-$DOWNVER/?version=tar-gz -O $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Download source"
 else
  echo "Source are exist..."
 fi


 switch_dir $srvDOWNDIR
 run "tar -xf $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Prepare source"
 switch_dir

 run "rm -rf $srvDIR/$APPNAME && rm -rf $srvBINDIR/$APPNAME-$APPVER" "Cleanup...."
 run "mkdir $srvBINDIR/$APPNAME-$APPVER && ln -s $srvBINDIR/$APPNAME-$APPVER $srvDIR/$APPNAME" "Make links"
 
 if [ ! -d $CONFDIR ]; then
   run "mkdir ${CONFDIR}" "Create empty config directory \"$CONFDIR\""
 fi
 

 #build main app
 switch_dir $srvDOWNDIR/$APPNAME-$APPVER
 run "./configure --prefix=$srvDIR/$APPNAME --sysconfdir=$CONFDIR --enable-delayed-ack --enable-dhcpv6 --enable-ipv4-pktinfo --enable-secs-byteorder --enable-binary-leases " "Configure application"
 run "make" "Compile project"
 run "make install" "Install project"
 switch_dir
 
 if [ -d "$srvDIR/$APPNAME" ]; then
   rm -rf $srvDIR/$APPNAME/etc
   ln -s ${CONFDIR} $srvDIR/$APPNAME/etc
 fi 
 
 
 run "adduser dhcpd -M --shell /sbin/nologin -d /tmp" "!Create user"
 run "mkdir /run/dhcpd && chown -R dhcpd:dhcpd /run/dhcpd" "!Create pid dirs"
 run "mkdir /var/dhcpd && mkdir /var/dhcpd/data && chown -R dhcpd:dhcpd /var/dhcpd" "!Create data dir"
 
 #echo -e "${COLOR_VALUE}Install $APPANAME service....${COLOR_END}"
 #service_install "$APPNAME" "$srvDIR/$APPNAME/sbin/$APPNAME" "forking"
}