#!/bin/bash

APPNAME=mpd
APPVER=0.19.10
DEPNAME1=ffmpeg
DEPVER1=2.8.1

mod_main(){
 if [ ! -f $srvDOWNDIR/$APPNAME-$APPVER.tar.gz ]; then
  run "wget http://www.musicpd.org/download/mpd/stable/$APPNAME-$APPVER.tar.gz -O $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Download source"
 else
  echo "Source are exist..."
 fi


 switch_dir $srvDOWNDIR
 run "tar -xf $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Prepare source"
 switch_dir

 run "rm -rf $srvDIR/$APPNAME && rm -rf $srvBINDIR/$APPNAME-$APPVER" "Cleanup...."
 run "mkdir $srvBINDIR/$APPNAME-$APPVER && ln -s $srvBINDIR/$APPNAME-$APPVER $srvDIR/$APPNAME" "Make links"


 #build main app
 switch_dir $srvDOWNDIR/$APPNAME-$APPVER
 run "./configure --prefix=$srvDIR/$APPNAME --enable-ffmpeg --enable-flac --enable-httpd-output --enable-id3 --enable-soundcloud --enable-lame-encoder --enable-pulse --enable-vorbis --enable-wavpack" "Configure application"
 run "make" "Compile project"
 run "make install" "Install project"
 switch_dir

 #echo -e "${COLOR_VALUE}Install $APPANAME service....${COLOR_END}"
 #service_install "$APPNAME" "$srvDIR/$APPNAME/sbin/$APPNAME" "forking"
}