#!/bin/bash

APPNAME=mpg123
APPVER=1.15.4

mod_main(){
 if [ ! -f $srvDOWNDIR/$APPNAME-$APPVER.tar.bz2 ]; then
  run "wget http://www.mpg123.de/download/$APPNAME-$APPVER.tar.bz2 -O $srvDOWNDIR/$APPNAME-$APPVER.tar.bz2" "Download source"
 else
  echo "Source downloading skipped as allready downloaded"
 fi
 
 if [ ! -z $ARG1 ]; then
   if [ "$ARG1" == "--download" ]; then
    die "Only download flag used"
   fi
   if [ "$ARG1" == "--help" ]; then
    die "--download - only download module"
   fi
 fi


 switch_dir $srvDOWNDIR
 run "tar -xf $srvDOWNDIR/$APPNAME-$APPVER.tar.bz2" "Prepare source"
 switch_dir

 #run "rm -rf $srvDIR/$APPNAME && rm -rf $srvBINDIR/$APPNAME-$APPVER" "Cleanup...."
 #run "mkdir $srvBINDIR/$APPNAME-$APPVER && ln -s $srvBINDIR/$APPNAME-$APPVER $srvDIR/$APPNAME" "Make links"


 switch_dir $srvDOWNDIR/$APPNAME-$APPVER

 run "./configure --prefix=/usr/local --enable-network --enable-ipv6 --with-default-audio=pulse --with-cpu=x86-64" "Make configuration"


 run "make" "Compile project"
 run "make install" "Install project"
 switch_dir
}


