#!/bin/bash

APPNAME=mysql
APPVER=5.7.11
DATADIR=$srvCONFDIR/$APPNAME/data
EXTERNAL_DEP="cmake gcc-c++ ncurses-devel"

mod_main(){
 #create users
 adduser -M -s /sbin/nologin mysql
 #============

 if [ ! -f $srvDOWNDIR/$APPNAME-$APPVER.tar.gz ]; then
  run "wget http://cdn.mysql.com/Downloads/MySQL-5.7/$APPNAME-$APPVER.tar.gz -O $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Download source"
 else
  echo "Source downloading skipped as allready downloaded"
 fi

 switch_dir $srvDOWNDIR
 run "tar -xf $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Prepare source"
 switch_dir

 run "rm -rf $srvDIR/$APPNAME && rm -rf $srvBINDIR/$APPNAME-$APPVER" "Cleanup...."
 run "mkdir $srvBINDIR/$APPNAME-$APPVER && ln -s $srvBINDIR/$APPNAME-$APPVER $srvDIR/$APPNAME" "Make links"


 switch_dir $srvDOWNDIR/$APPNAME-$APPVER

 run "cmake . -DCURSES_LIBRARY=/usr/lib64/libncurses.so -DDOWNLOAD_BOOST=1 -DWITH_BOOST=$srvDOWNDIR -DCURSES_INCLUDE_PATH=/usr/include -DWITH_INNOBASE_STORAGE_ENGINE=1 -DSYSCONFDIR=$srvCONFDIR/$APPNAME -DMYSQL_DATADIR=$DATADIR -DCMAKE_INSTALL_PREFIX=$srvDIR/$APPNAME -Wdeprecated-declarations,misleading-indentation,virtual-move-assign" "cMake configuration"

 run "mkdir -p $DATADIR" "Make data dir"
 run "make -j12" "Compile project"
 run "make install" "Install project"
 switch_dir
 
 switch_dir $srvDIR/$APPNAME
 run "bin/mysqld --initialize" "Initialize database"
 switch_dir

 echo -e "${COLOR_VALUE}Install $APPANAME service....${COLOR_END}"
 service_install "$APPNAME" "$srvDIR/$APPNAME/bin/${APPNAME}d_safe"
 
 alternatives --install /usr/bin/mysqld mysqld $srvDIR/$APPNAME/bin/mysqld 10
 alternatives --install /usr/bin/mysql mysql $srvDIR/$APPNAME/bin/mysql 10
}
