#!/bin/bash

APPNAME=php
APPVER=7.0.7
EXTERNAL_DEP="libxml2-devel bzip2-devel libcurl-devel gd libjpeg-turbo-devel libpng-devel freetype-devel libmcrypt-devel"


mod_main(){
 if [ ! -f $srvDOWNDIR/$APPNAME-$APPVER.tar.gz ]; then
  run "wget http://ch1.php.net/distributions/$APPNAME-$APPVER.tar.gz -O $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Download source"
 else
  echo "Source downloading skipped as allready downloaded"
 fi

 switch_dir $srvDOWNDIR
 run "tar -xf $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Prepare source"
 switch_dir

 run "rm -rf $srvDIR/$APPNAME && rm -rf $srvBINDIR/$APPNAME-$APPVER" "Cleanup...."
 run "mkdir $srvBINDIR/$APPNAME-$APPVER && ln -s $srvBINDIR/$APPNAME-$APPVER $srvDIR/$APPNAME" "Make links"


 switch_dir $srvDOWNDIR/$APPNAME-$APPVER

 export LD_LIBRARY_PATH=/usr/srv/mysql/lib

 run "./configure --prefix=$srvDIR/$APPNAME --with-config-file-path=$srvCONFDIR/$APPNAME --with-config-file-scan-dir=$srvCONFDIR/$APPNAME/ini --enable-fpm 
--with-mysql=/usr/srv/mysql --with-zlib --with-gd --enable--sysvsem --enable-sysvmsg --enable-sysvshm --enable-mbstring --enable-inline-optimization --disable-debug --enable-ipv6 --with-curl --with-jpeg-dir --disable-rpath --with-gettext --enable-bcmath 
--disable-inifile --disable-flatfile --without-cdb --with-freetype-dir --enable-sockets --with-bz2 --enable-ftp --with-mcrypt --with-xmlrpc --with-openssl --enable-opcache=no --with-pear" "Configuring project"

 run "make" "Compile project"
 run "make install" "Install project"
 switch_dir

 echo -e "${COLOR_VALUE}Install $APPANAME service....${COLOR_END}"
 service_install "$APPNAME" "$srvDIR/$APPNAME/sbin/$APPNAME-fpm --fpm-config=$srvCONFDIR/$APPNAME/php-fpm.conf" "forking"
}
