#!/bin/bash

APPNAME=samba
APPVER=4.4.3
EXTERNAL_DEP="python-devel python3-devel gnutls-devel libacl-devel openldap-devel"
INTERNAL_DEP=""


mod_main(){
 if [ ! -f $srvDOWNDIR/$APPNAME-$APPVER.tar.gz ]; then
  run "wget http://ftp.samba.org/pub/samba/$APPNAME-$APPVER.tar.gz -O $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Download source"
else
  echo "Source downloading skipped as allready downloaded"
 fi

 switch_dir $srvDOWNDIR
 run "tar -xf $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Prepare source"
 switch_dir

 run "rm -rf $srvDIR/$APPNAME && rm -rf $srvBINDIR/$APPNAME-$APPVER" "Cleanup...."
 run "mkdir $srvBINDIR/$APPNAME-$APPVER && ln -s $srvBINDIR/$APPNAME-$APPVER $srvDIR/$APPNAME" "Make links"


 switch_dir $srvDOWNDIR/$APPNAME-$APPVER

 run "./configure --prefix=$srvDIR/$APPNAME --with-configdir=$srvCONFDIR/$APPNAME" "Make configuration"

 run "make" "Compile project"
 run "make install" "Install project"
 switch_dir

 service_install "$APPNAME" "$srvDIR/$APPNAME/sbin/smbd -D --configfile=$srvCONFDIR/$APPNAME/smb.conf" "forking"
}
