#!/bin/bash

APPNAME=subversion
APPVER=1.8.0

mod_main(){
 if [ ! -f $srvDOWNDIR/$APPNAME-$APPVER.tar.gz ]; then
  run "wget http://apache.mesi.com.ar/$APPNAME/$APPNAME-$APPVER.tar.gz -O $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Download source"
 else
  echo "Source downloading skipped as allready downloaded"
 fi


 switch_dir $srvDOWNDIR
 run "tar -xf $srvDOWNDIR/$APPNAME-$APPVER.tar.gz" "Prepare source"
 switch_dir

 run "rm -rf $srvDIR/$APPNAME && rm -rf $srvBINDIR/$APPNAME-$APPVER" "Cleanup...."
 run "mkdir $srvBINDIR/$APPNAME-$APPVER && ln -s $srvBINDIR/$APPNAME-$APPVER $srvDIR/$APPNAME" "Make links"


 switch_dir $srvDOWNDIR/$APPNAME-$APPVER
 run "./configure --prefix=$srvDIR/$APPNAME" "Configure project"
 run "make" "Compile project"
 run "make install" "Install project"
 switch_dir

 echo -e "${COLOR_VALUE}Install $APPANAME service....${COLOR_END}"
 service_install "$APPNAME" "$srvDIR/$APPNAME/bin/$APPNAME --daemon --root $srvBINDIR/svn-data --listen-port 3690" "forking"
}
